### ISSUE TITLE
Fix credibility mapping rules for claim similarity (returning not_credible)

### ISSUE THREAD

**Issue by rdenaux** [co-inform/Gateway#39]
It seems something's wrong with the aggregation rules. In this example:

```json
"rule_engine": {
  "final_credibility": "not_credible",
  "module_labels": {
  "claim_similarity": "not_credible",
  "misinfome": "not_verifiable"
},
"module_values": {
  "claim_similarity": {
    "confidence": 0.7957837026957462,
    "credibility": 1
  },
  "misinfome": {
    "confidence": 0,
    "credibility": 0
  }
}
}
```

claim similarity is returning credibility value 1, but this is getting translated as `not_credible`, which is incorrect.

**Comment by AkramSadat** [comment]
Hi Ronald, aggregation rules, decide based on credibility and confidence values from all the modules, claim_similarity, misinfome and content analysis. Here I don't think the problem is from aggregation rules, because for claim_similarity it assigns not_credible as module_label. However based on our rule for claim_similarity, it should return credible. 

https://github.com/co-inform/policy_manager/blob/788798f87a6a239c775c32489984ea2680b77115/src/main/resources/rules/deployment/credibility_mapping/claim_credibility.json#L6

Here we define if confidence is higher than 0.7 and credibility is higher that 0.5, for this module the label is credible.

**Comment by rdenaux** [comment]
Thanks Akram, I renamed the issue to better reflect the problem. In that case, it looks like rules in lines 22 and [33](https://github.com/co-inform/policy_manager/blob/788798f87a6a239c775c32489984ea2680b77115/src/main/resources/rules/deployment/credibility_mapping/claim_credibility.json#L33) are incorrect and need to be fixed

**Comment by AkramSadat** [comment]
Thanks 😊  I fixed the rules that you mentioned in master branch.

**Comment by rdenaux** [comment]
Great! When do these changes get propagated to the production deployment? Once I verify it works there, I'll close this issue.

**Comment by rdenaux** [comment]
Hi @AkramSadat, I was reviewing the changes and I think there's still an issue. None of the rules match credibilities between -0.25 and 0.25. 
Also, the < or <= are not applied consistently, so in some corner cases like credibility exactly 0.5 will not match, while others match 2 rules (exactly -0.5)

**Comment by AkramSadat** [comment]
Hi @rdenaux, Thanks. I am going to review all the rules, I also noticed some inconsistency between rules.

**Comment by daffyDukk** [comment]
This has been deployed yesterday so ones you have verified that it works just close this @rdenaux

**Comment by rdenaux** [comment]
Verified; it works as expected now 👍
